# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vf-Nc17avqg6Nu57_JvBk6Dcqb014Q8o
"""

age=int(input("Enter your age: "))
if(age<=15):
    print('you are infant')
elif(age>15 and age<18):
    print('you are child')
elif(age>=18 and age <22):
    print('you are teenager')
elif(age>=22 and age<50):
    print('you are Adult')
else:
    print('you are under senior citizen')